// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: build.sql

package store

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const getBuildByJobNumber = `-- name: GetBuildByJobNumber :one
SELECT
    id,
    repository_id,
    job_name,
    build_number,
    branch,
    pr_number,
    commit_sha,
    result,
    started_at,
    finished_at,
    duration_ms,
    agent_name,
    agent_instance_type,
    agent_lifecycle,
    infra_failure,
    infra_reason,
    cost_usd,
    created_at,
    updated_at
FROM build
WHERE job_name = $1 AND build_number = $2
`

type GetBuildByJobNumberParams struct {
	JobName     string
	BuildNumber int32
}

type GetBuildByJobNumberRow struct {
	ID                int64
	RepositoryID      int64
	JobName           string
	BuildNumber       int32
	Branch            string
	PrNumber          *int32
	CommitSha         string
	Result            string
	StartedAt         *time.Time
	FinishedAt        *time.Time
	DurationMs        *int64
	AgentName         *string
	AgentInstanceType *string
	AgentLifecycle    string
	InfraFailure      bool
	InfraReason       *string
	CostUsd           pgtype.Numeric
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

func (q *Queries) GetBuildByJobNumber(ctx context.Context, arg GetBuildByJobNumberParams) (GetBuildByJobNumberRow, error) {
	row := q.db.QueryRow(ctx, getBuildByJobNumber, arg.JobName, arg.BuildNumber)
	var i GetBuildByJobNumberRow
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.JobName,
		&i.BuildNumber,
		&i.Branch,
		&i.PrNumber,
		&i.CommitSha,
		&i.Result,
		&i.StartedAt,
		&i.FinishedAt,
		&i.DurationMs,
		&i.AgentName,
		&i.AgentInstanceType,
		&i.AgentLifecycle,
		&i.InfraFailure,
		&i.InfraReason,
		&i.CostUsd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
