// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ingest.sql

package store

import (
	"context"
	"time"
)

const deleteStageRunsByBuild = `-- name: DeleteStageRunsByBuild :exec
DELETE FROM stage_run WHERE build_id = $1
`

func (q *Queries) DeleteStageRunsByBuild(ctx context.Context, buildID int64) error {
	_, err := q.db.Exec(ctx, deleteStageRunsByBuild, buildID)
	return err
}

const deleteTestRunsByBuild = `-- name: DeleteTestRunsByBuild :exec
DELETE FROM test_run WHERE build_id = $1
`

func (q *Queries) DeleteTestRunsByBuild(ctx context.Context, buildID int64) error {
	_, err := q.db.Exec(ctx, deleteTestRunsByBuild, buildID)
	return err
}

const getBuildByID = `-- name: GetBuildByID :one
SELECT
    b.id,
    r.name AS repository_name,
    b.job_name,
    b.build_number,
    b.branch,
    b.pr_number,
    b.commit_sha,
    b.result,
    b.started_at,
    b.finished_at,
    b.duration_ms,
    b.agent_name,
    b.agent_lifecycle,
    b.log_tail
FROM build b
JOIN repository r ON r.id = b.repository_id
WHERE b.id = $1
`

type GetBuildByIDRow struct {
	ID             int64
	RepositoryName string
	JobName        string
	BuildNumber    int32
	Branch         string
	PrNumber       *int32
	CommitSha      string
	Result         string
	StartedAt      *time.Time
	FinishedAt     *time.Time
	DurationMs     *int64
	AgentName      *string
	AgentLifecycle string
	LogTail        *string
}

func (q *Queries) GetBuildByID(ctx context.Context, id int64) (GetBuildByIDRow, error) {
	row := q.db.QueryRow(ctx, getBuildByID, id)
	var i GetBuildByIDRow
	err := row.Scan(
		&i.ID,
		&i.RepositoryName,
		&i.JobName,
		&i.BuildNumber,
		&i.Branch,
		&i.PrNumber,
		&i.CommitSha,
		&i.Result,
		&i.StartedAt,
		&i.FinishedAt,
		&i.DurationMs,
		&i.AgentName,
		&i.AgentLifecycle,
		&i.LogTail,
	)
	return i, err
}

const getOrCreateRepository = `-- name: GetOrCreateRepository :one
INSERT INTO repository (name)
VALUES ($1)
ON CONFLICT (name) DO UPDATE
SET name = repository.name
RETURNING id
`

func (q *Queries) GetOrCreateRepository(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRow(ctx, getOrCreateRepository, name)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertStageRun = `-- name: InsertStageRun :exec
INSERT INTO stage_run (build_id, name, started_at, duration_ms, result)
VALUES ($1, $2, $3, $4, $5)
`

type InsertStageRunParams struct {
	BuildID    int64
	Name       string
	StartedAt  *time.Time
	DurationMs int64
	Result     string
}

func (q *Queries) InsertStageRun(ctx context.Context, arg InsertStageRunParams) error {
	_, err := q.db.Exec(ctx, insertStageRun,
		arg.BuildID,
		arg.Name,
		arg.StartedAt,
		arg.DurationMs,
		arg.Result,
	)
	return err
}

const insertTestRun = `-- name: InsertTestRun :exec
INSERT INTO test_run (
    build_id,
    test_case_id,
    outcome,
    duration_ms,
    rerun_failures,
    failure_type,
    failure_hash,
    stage
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, 'BLOCKING'
)
`

type InsertTestRunParams struct {
	BuildID       int64
	TestCaseID    int64
	Outcome       string
	DurationMs    int64
	RerunFailures int32
	FailureType   *string
	FailureHash   *string
}

func (q *Queries) InsertTestRun(ctx context.Context, arg InsertTestRunParams) error {
	_, err := q.db.Exec(ctx, insertTestRun,
		arg.BuildID,
		arg.TestCaseID,
		arg.Outcome,
		arg.DurationMs,
		arg.RerunFailures,
		arg.FailureType,
		arg.FailureHash,
	)
	return err
}

const listStageRunsByBuild = `-- name: ListStageRunsByBuild :many
SELECT id, name, started_at, duration_ms, result
FROM stage_run
WHERE build_id = $1
ORDER BY id
`

type ListStageRunsByBuildRow struct {
	ID         int64
	Name       string
	StartedAt  *time.Time
	DurationMs int64
	Result     string
}

func (q *Queries) ListStageRunsByBuild(ctx context.Context, buildID int64) ([]ListStageRunsByBuildRow, error) {
	rows, err := q.db.Query(ctx, listStageRunsByBuild, buildID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStageRunsByBuildRow{}
	for rows.Next() {
		var i ListStageRunsByBuildRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.StartedAt,
			&i.DurationMs,
			&i.Result,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTestRunsByBuild = `-- name: ListTestRunsByBuild :many
SELECT
    tr.id,
    tc.module,
    tc.class_name,
    tc.method_name,
    tr.outcome,
    tr.duration_ms,
    tr.rerun_failures,
    tr.failure_type,
    tr.failure_hash,
    tr.stage
FROM test_run tr
JOIN test_case tc ON tc.id = tr.test_case_id
WHERE tr.build_id = $1
ORDER BY tc.class_name, tc.method_name, tr.id
`

type ListTestRunsByBuildRow struct {
	ID            int64
	Module        string
	ClassName     string
	MethodName    string
	Outcome       string
	DurationMs    int64
	RerunFailures int32
	FailureType   *string
	FailureHash   *string
	Stage         string
}

func (q *Queries) ListTestRunsByBuild(ctx context.Context, buildID int64) ([]ListTestRunsByBuildRow, error) {
	rows, err := q.db.Query(ctx, listTestRunsByBuild, buildID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTestRunsByBuildRow{}
	for rows.Next() {
		var i ListTestRunsByBuildRow
		if err := rows.Scan(
			&i.ID,
			&i.Module,
			&i.ClassName,
			&i.MethodName,
			&i.Outcome,
			&i.DurationMs,
			&i.RerunFailures,
			&i.FailureType,
			&i.FailureHash,
			&i.Stage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertBuild = `-- name: UpsertBuild :one
INSERT INTO build (
    repository_id,
    job_name,
    build_number,
    branch,
    pr_number,
    commit_sha,
    result,
    started_at,
    finished_at,
    duration_ms,
    agent_name,
    agent_lifecycle,
    log_tail
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, 'LOCAL', $12
)
ON CONFLICT (job_name, build_number) DO UPDATE
SET repository_id = EXCLUDED.repository_id,
    branch = EXCLUDED.branch,
    pr_number = EXCLUDED.pr_number,
    commit_sha = EXCLUDED.commit_sha,
    result = EXCLUDED.result,
    started_at = EXCLUDED.started_at,
    finished_at = EXCLUDED.finished_at,
    duration_ms = EXCLUDED.duration_ms,
    agent_name = EXCLUDED.agent_name,
    agent_lifecycle = EXCLUDED.agent_lifecycle,
    log_tail = EXCLUDED.log_tail,
    updated_at = now()
RETURNING id
`

type UpsertBuildParams struct {
	RepositoryID int64
	JobName      string
	BuildNumber  int32
	Branch       string
	PrNumber     *int32
	CommitSha    string
	Result       string
	StartedAt    *time.Time
	FinishedAt   *time.Time
	DurationMs   *int64
	AgentName    *string
	LogTail      *string
}

func (q *Queries) UpsertBuild(ctx context.Context, arg UpsertBuildParams) (int64, error) {
	row := q.db.QueryRow(ctx, upsertBuild,
		arg.RepositoryID,
		arg.JobName,
		arg.BuildNumber,
		arg.Branch,
		arg.PrNumber,
		arg.CommitSha,
		arg.Result,
		arg.StartedAt,
		arg.FinishedAt,
		arg.DurationMs,
		arg.AgentName,
		arg.LogTail,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const upsertTestCase = `-- name: UpsertTestCase :one
INSERT INTO test_case (repository_id, module, class_name, method_name)
VALUES ($1, $2, $3, $4)
ON CONFLICT (repository_id, class_name, method_name) DO UPDATE
SET module = EXCLUDED.module
RETURNING id
`

type UpsertTestCaseParams struct {
	RepositoryID int64
	Module       string
	ClassName    string
	MethodName   string
}

func (q *Queries) UpsertTestCase(ctx context.Context, arg UpsertTestCaseParams) (int64, error) {
	row := q.db.QueryRow(ctx, upsertTestCase,
		arg.RepositoryID,
		arg.Module,
		arg.ClassName,
		arg.MethodName,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
