// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: repository.sql

package store

import (
	"context"
)

const getRepositoryByName = `-- name: GetRepositoryByName :one
SELECT id, name, default_branch, created_at
FROM repository
WHERE name = $1
`

func (q *Queries) GetRepositoryByName(ctx context.Context, name string) (Repository, error) {
	row := q.db.QueryRow(ctx, getRepositoryByName, name)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DefaultBranch,
		&i.CreatedAt,
	)
	return i, err
}

const upsertRepository = `-- name: UpsertRepository :one
INSERT INTO repository (name, default_branch)
VALUES ($1, $2)
ON CONFLICT (name) DO UPDATE
SET default_branch = EXCLUDED.default_branch
RETURNING id, name, default_branch, created_at
`

type UpsertRepositoryParams struct {
	Name          string
	DefaultBranch string
}

func (q *Queries) UpsertRepository(ctx context.Context, arg UpsertRepositoryParams) (Repository, error) {
	row := q.db.QueryRow(ctx, upsertRepository, arg.Name, arg.DefaultBranch)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DefaultBranch,
		&i.CreatedAt,
	)
	return i, err
}
